import type { Prisma, PrismaClient } from "@prisma/client";
import { DeliverableStatus, AppointmentStatus } from "@prisma/client";
import { prisma as defaultPrisma } from "@/lib/prisma";
import { ApiError } from "@/lib/errors";
import type { Logger } from "@/lib/logger";

/**
 * In-app notifications (P4). Reminders are generated by a periodic scan and
 * made idempotent via `dedupeKey` (a unique per-notification key), so re-runs
 * never duplicate. Users read their own notifications; marking read is scoped
 * to the owner.
 */
type Db = PrismaClient | Prisma.TransactionClient;

export interface CreateNotificationInput {
  userId: string;
  type: string;
  title: string;
  body?: string | null;
  href?: string | null;
  dedupeKey?: string | null;
}

/** Create a notification; if a dedupeKey collides, silently no-op. */
export async function createNotification(input: CreateNotificationInput, opts: { db?: Db } = {}) {
  const db = opts.db ?? defaultPrisma;
  if (input.dedupeKey) {
    const existing = await db.notification.findUnique({ where: { dedupeKey: input.dedupeKey }, select: { id: true } });
    if (existing) return null;
  }
  return db.notification.create({
    data: {
      userId: input.userId,
      type: input.type,
      title: input.title,
      body: input.body ?? null,
      href: input.href ?? null,
      dedupeKey: input.dedupeKey ?? null,
    },
  });
}

export async function listNotifications(userId: string, opts: { db?: Db; limit?: number } = {}) {
  const db = opts.db ?? defaultPrisma;
  return db.notification.findMany({
    where: { userId },
    orderBy: { createdAt: "desc" },
    take: opts.limit ?? 30,
  });
}

export async function unreadCount(userId: string, opts: { db?: Db } = {}) {
  const db = opts.db ?? defaultPrisma;
  return db.notification.count({ where: { userId, readAt: null } });
}

/** Mark one notification read — scoped to its owner (no cross-user writes). */
export async function markRead(id: string, userId: string, opts: { db?: Db } = {}) {
  const db = opts.db ?? defaultPrisma;
  const res = await db.notification.updateMany({ where: { id, userId, readAt: null }, data: { readAt: new Date() } });
  if (res.count === 0) {
    const exists = await db.notification.findFirst({ where: { id, userId }, select: { id: true } });
    if (!exists) throw ApiError.notFound("Notification not found");
  }
}

export async function markAllRead(userId: string, opts: { db?: Db } = {}) {
  const db = opts.db ?? defaultPrisma;
  await db.notification.updateMany({ where: { userId, readAt: null }, data: { readAt: new Date() } });
}

/**
 * Scan for things worth reminding people about and create notifications
 * (idempotent). Returns how many were newly created.
 *   - Appointments starting within the next 24h → remind the host.
 *   - Deliverables past due and not done → nudge the owner (once).
 */
export async function generateReminders(opts: { db?: Db; now?: Date; log?: Logger } = {}) {
  const db = opts.db ?? defaultPrisma;
  const now = opts.now ?? new Date();
  const in24h = new Date(now.getTime() + 24 * 60 * 60 * 1000);
  let created = 0;

  const upcoming = await db.appointment.findMany({
    where: { status: AppointmentStatus.scheduled, startAt: { gte: now, lt: in24h } },
    select: { id: true, title: true, startAt: true, ownerId: true },
  });
  for (const a of upcoming) {
    const n = await createNotification(
      {
        userId: a.ownerId,
        type: "appointment_reminder",
        title: `Upcoming: ${a.title}`,
        body: `Starts ${a.startAt.toLocaleString()}`,
        href: "/calendar",
        dedupeKey: `appt:${a.id}`,
      },
      { db },
    );
    if (n) created++;
  }

  const overdue = await db.deliverable.findMany({
    where: { deletedAt: null, status: { not: DeliverableStatus.done }, dueDate: { lt: now }, ownerId: { not: null } },
    select: { id: true, title: true, ownerId: true, projectId: true },
  });
  for (const d of overdue) {
    const n = await createNotification(
      {
        userId: d.ownerId!,
        type: "task_overdue",
        title: `Overdue task: ${d.title}`,
        href: `/projects/${d.projectId}`,
        dedupeKey: `overdue:${d.id}`,
      },
      { db },
    );
    if (n) created++;
  }

  opts.log?.info({ created, scannedAppointments: upcoming.length, scannedOverdue: overdue.length }, "reminder scan complete");
  return { created };
}
